### ISSUE TITLE
Can't Reproduce Results: Tensorflow==1.15 not available on pip any more 

### ISSUE THREAD

**Issue by ali-chaudhry8** [google/ml-fairness-gym#10]
Do you have a github version of this ml-fairness-code with tensorflow 1.8 or later? Currently requirements.txt uses tensorflow==1.15 which is not available for pip installation anymore. I have tensorflow 1.8 but that (obviously) creates a lot of dependancies issues. I am struggling to reproduce the results. 

Please let me know.

Many thanks,
Ali

**Comment by yhalpern** [comment]
Hi Ali,
tensorflow 1.15 is the final version of tensorflow 1.x and it looks like it is supported. Can you try to follow the instructions here?
https://www.tensorflow.org/install/pip?lang=python3#older-versions-of-tensorflow

`pip install --upgrade tensorflow==1.15` seems to work fine for me.

**Comment by ali-chaudhry8** [comment]
Thanks Yoni. When I install tensorflow, it says requirements satisfied but when I import tensorflow it gives a syntax error: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.8/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/python3.8/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/ali/Documents/Reinforcement_Learning/ml-fairness-gym/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/tensorflow/python/pywrap_tensorflow_internal.py", line 114
    def TFE_ContextOptionsSetAsync(arg1, async):

Do you think this might be because i have python 3.8?

**Comment by hansa0** [comment]
Hi Ali,

Yes that may be the problem. From the Tensorflow installation website ([https://www.tensorflow.org/install/pip](https://www.tensorflow.org/install/pip)), it seems the supported versions of python are 3.5-3.7.

Can you try installing and running with python 3.7?
